openapi: "3.0.0"
info:
  version: 1.0.0
  title: WebAPP API
servers:
  - url: http://localhost:8888
paths:
  /addresses:
    get:


  /bond/term:
    post:
      summary: "POST request to create Bond Term"
