openapi: "3.0.0"
info:
  version: 1.0.0
  title: Corda API
servers:
  - url: http://localhost:9091
paths:
  /corda/{apiId}:
    get:
      summary: get the address for the corda nodes
      operationId: get-corda-details
      tags:
        - corda-info
      parameters:
        - name: apiId
          in: path
          required: true
          description: The API to query on the corda network
          schema:
            type: string
      responses:
        '200':
          description: Retrieved the addresses
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/terms/issue:
    post:
      summary: Create Bond Term
      operationId: issue-bond-terms
      tags:
        - corda
        - create-term
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/termRequest'
      responses:
        '200':
          description: Response for create Term
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/termCreateResponse'
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/terms/query:
    post:
      summary: API to query for Terms
      operationId: query-bond-terms
      tags:
        - corda
        - query-term
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                queryType:
                  type: string
                  enum:
                    - byCurrency
                    - byRating
                    - lessThanMaturityDate
                    - greaterThanMaturityDate
                    - byTermStateLinearID
                queryValue:
                  type: string
      responses:
        '200':
          description: Response for create Term
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/bonds/issue:
    post:
      summary: POST API to issue bond
      operationId: issue-bond
      tags:
        - corda
        - issue-bond
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teamStateLinearID:
                  type: string
                unitsOfBonds:
                  type: integer
      responses:
        '200':
          description: Response for Bond Issuance
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/bonds/query:
    post:
      summary: API to query for Terms
      operationId: query-bonds
      tags:
        - corda
        - query-bonds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                queryType:
                  type: string
                  enum:
                    - byCurrency
                    - byRating
                    - lessThanMaturityDate
                    - greaterThanMaturityDate
                    - byTermStateLinearID
                queryValue:
                  type: string
      responses:
        '200':
          description: Response for create Term
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/bonds/tokens/{termId}:
    get:
      summary: Get bond tokens issued to the user firing this query
      operationId: get-bond-tokens
      tags:
        - corda
        - query-bond-tokens
      parameters:
        - name: termId
          in: path
          required: true
          description: The linearId stored in corda for state objects
          schema:
            type: string
      responses:
        '200':
          description: Retrieve the total tokens on this bond
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
components:
  schemas:
    termRequest:
      type: object
      properties:
        bondName:
          type: string
        couponPaymentLeft:
          type: number
        interestRate:
          type: number
        purchasePrice:
          type: number
        unitsAvailable:
          type: number
        maturityDate:
          type: string
        bondType:
          type: string
        currency:
          type: string
        creditRating:
          type: string
        paymentsPerYear:
          type: number
    termCreateResponse:
      type: object
      properties:
        transactionID:
          type: string
        bondName:
          type: string
        purchasePrice:
          type: string
        linearId:
          type: string
    messageStatusCode:
      type: object
      properties:
        msg:
          type: string
        code:
          type: string
