openapi: "3.0.0"
info:
  version: 1.0.0
  title: Corda API
servers:
  - url: http://localhost:9091
paths:
  ## Node API
  /corda/{apiId}:
    get:
      summary: get the address for the corda nodes
      operationId: get-corda-details
      tags:
        - corda-info
      parameters:
        - name: apiId
          in: path
          required: true
          description: The API to query on the corda network
          schema:
            type: string
      responses:
        '200':
          description: Retrieved the addresses
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'

  ## Terms API
  /corda/terms/issue:
    post:
      summary: Create Bond Term
      operationId: issue-bond-terms
      tags:
        - corda
        - create-term
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/termRequest'
      responses:
        '200':
          description: Response for create Term
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/termCreateResponse'
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/terms/query:
    post:
      summary: API to query for Terms
      operationId: query-bond-terms
      tags:
        - corda
        - query-term
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                queryType:
                  type: string
                  enum:
                    - byCurrency
                    - byRating
                    - lessThanMaturityDate
                    - greaterThanMaturityDate
                    - byTermStateLinearID
                    - notActiveBonds
                queryValue:
                  type: string
      responses:
        '200':
          description: Response for create Term
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'

  ## Bonds API
  /corda/bonds/issue:
    post:
      summary: POST API to issue bond
      operationId: issue-bond
      tags:
        - corda
        - issue-bond
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teamStateLinearID:
                  type: string
                unitsOfBonds:
                  type: integer
      responses:
        '200':
          description: Response for Bond Issuance
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/bonds/query:
    post:
      summary: API to query for Terms
      operationId: query-bonds
      tags:
        - corda
        - query-bonds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                queryType:
                  type: string
                  enum:
                    - byCurrency
                    - byRating
                    - lessThanMaturityDate
                    - greaterThanMaturityDate
                    - byTermStateLinearID
                    - notActiveBonds
                queryValue:
                  type: string
      responses:
        '200':
          description: Response for create Term
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/bonds/tokens/{termId}:
    get:
      summary: Get bond tokens issued to the user firing this query
      operationId: get-bond-tokens
      tags:
        - corda
        - query-bond-tokens
      parameters:
        - name: termId
          in: path
          required: true
          description: The linearId stored in corda for state objects
          schema:
            type: string
      responses:
        '200':
          description: Retrieve the total tokens on this bond
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'

  ## Coupon and Redemption API
  /corda/bond/coupon/payment:
    post:
      summary: POST API to pay coupons to various holders of the bond
      operationId: bond-coupon
      tags:
        - corda
        - bond-coupon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                couponDate:
                  type: string
      responses:
        '200':
          description: Response for coupon payment
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/bond/redeem/early:
    post:
      summary: POST API to Early redemption of bonds
      operationId: bond-early-redemption
      tags:
        - corda
        - bond-redeem-early
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                termId:
                  type: string
      responses:
        '200':
          description: Response for coupon payment
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/bond/redeem:
    post:
      summary: POST API to redemption of bonds
      operationId: bond-redemption
      tags:
        - corda
        - bond-redeem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                maturityDate:
                  type: string
      responses:
        '200':
          description: Response for coupon payment
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'

  ## CASH API
  /corda/cash:
    get:
      summary: Get cash tokens
      operationId: get-cash-tokens
      tags:
        - corda
        - query-cash-tokens
      responses:
        '200':
          description: Retrieve the total tokens on this bond
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/cash/issue:
    post:
      summary: POST API to create money in the central bank
      operationId: issue-cash
      tags:
        - corda
        - issue-cash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                currencyCode:
                  type: string
                usdRate:
                  type: number
      responses:
        '200':
          description: Response for Bond Issuance
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/cash/query:
    post:
      summary: API to query for cash
      operationId: query-cash
      tags:
        - corda
        - query-cash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                queryType:
                  type: string
                  enum:
                    - byCurrencyCode
                queryValue:
                  type: string
      responses:
        '200':
          description: Response for create Term
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'
  /corda/cash/transfer:
    post:
      summary: POST API to transfer money to other parties
      operationId: transfer-cash
      tags:
        - corda
        - transfer-cash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                currencyCode:
                  type: string
                recipient:
                  type: string
      responses:
        '200':
          description: Response for Bond Issuance
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: The request has been accepted for processing, but the processing has not been completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageStatusCode'

components:
  schemas:
    termRequest:
      type: object
      properties:
        bondName:
          type: string
        interestRate:
          type: number
        parValue:
          type: number
        unitsAvailable:
          type: integer
        maturityDate:
          type: string
        bondType:
          type: string
        currency:
          type: string
        creditRating:
          type: string
        paymentFrequencyInMonths:
          type: integer
    termCreateResponse:
      type: object
      properties:
        transactionID:
          type: string
        bondName:
          type: string
        parValue:
          type: string
        linearId:
          type: string
    messageStatusCode:
      type: object
      properties:
        msg:
          type: string
        code:
          type: string
