###
GET http://{{host}}:{{port}}/corda/addresses

###
GET http://{{host}}:{{port}}/corda/identities

###
GET http://{{host}}:{{port}}/corda/platformversion

###
GET http://{{host}}:{{port}}/corda/peers

###
GET http://{{host}}:{{port}}/corda/notaries

###
GET http://{{host}}:{{port}}/corda/flows

###
GET http://{{host}}:{{port}}/corda/me

###
GET http://{{host}}:{{port}}/corda/states

### Create Term
POST http://{{host}}:{{port}}/corda/terms/issue
Content-Type: application/json

{
  "bondName": "GS-30Y-TB-NY",
  "interestRate": 1.2,
  "parValue": 200,
  "unitsAvailable": 1200,
  "maturityDate": "20320907",
  "bondType": "TB",
  "currency": "USD",
  "creditRating": "AAA",
  "paymentFrequencyInMonths": 4
}


### Query Terms
POST http://{{host}}:{{port}}/corda/terms/query
Content-Type: application/json

{
  "queryType": "lessThanMaturityDate",
  "queryValue": "20420101"
}

### Issue Bonds
POST http://{{host}}:{{port}}/corda/bonds/issue
Content-Type: application/json

{
  "teamStateLinearID": "e0ed4ee6-ea6a-4abc-9f73-bb5823da21ac",
  "unitsOfBonds": 56
}

### Query Bonds

### Query Bonds by termId
POST http://{{host}}:{{port}}/corda/bonds/query
Content-Type: application/json

{
  "queryType": "byTermStateLinearID",
  "queryValue": "e0ed4ee6-ea6a-4abc-9f73-bb5823da21ac"
}

### Query Bond Tokens by TermId
GET http://{{host}}:{{port}}/corda/bonds/tokens/e0ed4ee6-ea6a-4abc-9f73-bb5823da21ac
Content-Type: application/json

### Coupon payment
POST http://{{host}}:{{port}}/corda/bond/coupon/payment
Content-Type: application/json

{
  "couponDate": "20220907"
}

### Early Redemption
POST http://{{host}}:{{port}}/corda/bond/redeem/early
Content-Type: application/json

{
  "termId": "e0ed4ee6-ea6a-4abc-9f73-bb5823da21ac"
}

### CASH
### Create Cash (used by CB)
POST http://{{host}}:{{port}}/corda/cash/issue
Content-Type: application/json

{
  "amount": "10000000000",
  "currencyCode": "USD",
  "usdRate": 1.0
}

### Query Cash By Currency
POST http://{{host}}:{{port}}/corda/cash/query
Content-Type: application/json

{
  "queryType": "byCurrencyCode",
  "queryValue": "USD"
}

### Query All Cash on the Node
GET http://{{host}}:{{port}}/corda/cash

### Transfer Cash to particular node
POST http://{{host}}:{{port}}/corda/cash/transfer
Content-Type: application/json

{
  "amount": "1000000000",
  "currencyCode": "USD",
  "recipient": "Goldman Sachs"
}
