###
GET http://{{host}}:{{port}}/corda/addresses

###
GET http://{{host}}:{{port}}/corda/identities

###
GET http://{{host}}:{{port}}/corda/platformversion

###
GET http://{{host}}:{{port}}/corda/peers

###
GET http://{{host}}:{{port}}/corda/notaries

###
GET http://{{host}}:{{port}}/corda/flows

###
GET http://{{host}}:{{port}}/corda/me

###
GET http://{{host}}:{{port}}/corda/states

###
POST http://{{host}}:{{port}}/corda/terms/issue
Content-Type: application/json

{
  "bondName": "GS-30Y-TB-USD",
  "interestRate": 12.0,
  "parValue": 1000,
  "unitsAvailable": 500,
  "maturityDate": "20320810",
  "bondType": "TB",
  "currency": "USD",
  "creditRating": "AAA",
  "paymentFrequencyInMonths": 6
}


###
POST http://{{host}}:{{port}}/corda/terms/query
Content-Type: application/json

{
  "queryType": "greaterThanMaturityDate",
  "queryValue": "20220812"
}

###
POST http://{{host}}:{{port}}/corda/bonds/issue
Content-Type: application/json

{
  "teamStateLinearID": "a7ffd03a-4ba6-496a-8130-fbea8f779c0e",
  "unitsOfBonds": 10
}

###
POST http://{{host}}:{{port}}/corda/bonds/query
Content-Type: application/json

{
  "queryType": "greaterThanMaturityDate",
  "queryValue": "20220812"
}

###
POST http://{{host}}:{{port}}/corda/bonds/query
Content-Type: application/json

{
  "queryType": "byTermStateLinearID",
  "queryValue": "a7ffd03a-4ba6-496a-8130-fbea8f779c0e"
}

###
GET http://{{host}}:{{port}}/corda/bonds/tokens/a7ffd03a-4ba6-496a-8130-fbea8f779c0e
Content-Type: application/json
